spring:
  datasource:
    url: jdbc:mysql://localhost:3306/maple-leaf-reading?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver



mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml        #sql映射文件位
  configuration:  # 指定mybatis全局配置文件中的相关配置项
      map-underscore-to-camel-case: true
